quchimcha = "E'tibor bering, bu umumiy chora-tadbirlar va samaradorlik fermaning o'ziga xos sharoitlariga qarab farq qilishi mumkin. Mintaqangizdagi eng yaxshi amaliyotlar uchun har doim mahalliy qishloq xo'jaligini kengaytirish xizmati yoki professional agronom bilan maslahatlashing. Bundan tashqari, har qanday pestitsidlar yoki fungitsidlardan foydalanganda har doim ishlab chiqaruvchining ko'rsatmalariga amal qiling."

data = {
  'Apple___Black_rot': 'Qora olma chirishi',
  'Apple___Cedar_apple_rust': 'Olma sadr zang',
  'Apple___healthy': "Olma sog'lom",
  'Apple___Apple_scab': "Olma qoraqo'tiri",
  'Cherry_(including_sour)___Powdery_mildew': 'Gilos kukunli chiriyotgan',
  'Cherry_(including_sour)___healthy': "Gilos sog'lom",
  'Grape___Esca_(Black_Measles)': 'Uzum qora qizamiq',
  'Grape___Black_rot': 'Qora uzum chirishi',
  'Grape_Isariopsis_Leaf_Spot': "Uzum Isariopsis barglari dog'i",
  'Grape_healthy': "Sog'lom uzum",
  'Corn_(maize)___Common_rust_': "Makkajo'xori oddiy zang",
  'Corn_fallarmyworm': "Makkajo'xori qurti",
  'Corn_grasshoper': "Makkajo'xori chigirtkasi",
  'Corn_(maize)___healthy': "Makkajo'xori sog'lom",
  'Corn_leaf_beetle': "Makkajo'xori bargi qo'ng'izi",
  'Corn_(maize)___Northern_Leaf_Blight': "Makkajo'xori barglari kuyishi",
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': "Makkajo'xori bargi dog'i",
  'Corn_streak_virus': "Makkajo'xori chizig'i virusi",
  'Peach___Bacterial_spot': "Shaftoli bakterial dog'i",
  'Peach___healthy': "Sog'lom shaftoli",
  'Pepper,_bell___healthy': "Qalampir, qo'ng'iroq sog'lom",
  'Pepper,_bell___Bacterial_spot': "Qalampir qo'ng'irog'i bakterial dog'",
  'Potato___Early_blight': 'Kartoshkaning erta kuyishi',
  'Potato___Late_blight': 'Kartoshkaning kech zararlanishi',
  'Potato___healthy': "Sog'lom kartoshka",
  'Strawberry___Leaf_scorch': 'Qulupnay barglari kuyishi',
  'Strawberry___healthy': "Sog'lom qulupnay",
  'Tomato___Bacterial_spot': 'Pomidorning bakterial joyi',
  'Tomato___Leaf_Mold': 'Pomidor barglari qolipi',
  'Tomato___Spider_mites Two-spotted_spider_mite': "Pomidor o'rgimchak oqadilar",
  'Tomato___healthy': "Pomidor sog'lom",
  'Tomato___Early_blight': 'Pomidor barglari kuyishi',
  "Tomato___Late_blight":"Pomidor barglari kuyishi",
  'Tomato_leaf_curl': 'Pomidor barglari jingalak',
  'Tomato___Tomato_mosaic_virus': 'Pomidor mozaikasi virusi',
  'Tomato___Septoria_leaf_spot': "Pomidor septoriya bargi dog'i",
  'Tomato_verticulium_wilt': "Pomidor verticillium so'lishi",
  "Tomato___Target_Spot":"Pamidorning zararlangan joyi",
  "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Pomidorning sariq barglari jingalak virusi",

}
tashxis = {
  "Apple___Black_rot" : "Kasal yoki chirigan daraxtlar yoki shoxlarni olib tashlang1. Daraxtlardan barcha quritilgan va chirigan mevalarni to'plang1. Har qanday potentsial ifloslangan o'simliklardan xalos bo'ling1. Barcha kasal o'simlik materiallari yondirilishi, ko'milishi yoki mahalliy kompostlash inshootiga olib kelinishi kerak1. Agar siz har qanday olma daraxtini kesishga qaror qilsangiz, dudoqlarni ham olib tashlashingiz kerak. Daraxt dumlarini parchalashda sporalar ajralishi mumkin1.",
  "Apple___Cedar_apple_rust" : "Xost o'simliklardan birini yo'q qiling2. Sidr-olma qo'ziqoriniga chidamli navlarni etishtirish2. Archaning zararlangan qismlarini (o'tlarini) kesish ham infektsiyalar ehtimolini ma'lum darajada kamaytirishi mumkin2. Fungitsidlarni qo'llash2.",
  "Apple___Apple_scab" : "Qo'tirga chidamli olma navlarini tanlang. Daraxtlarni to'g'ri eking. Infektsiyalangan barglarni kesib oling. Sug'orish jadvalini o'zgartiring.Kompost bilan yoping. Nam oltingugurtdan foydalaning. Fungitsidlarni qo'llang. Yiqilgan barglarning parchalanishini kuchaytirish va ularni yomg'ir qurtlari uchun yanada mazali qilish uchun kuzda erga tushgan barglarga azot qo'llang. Parchalanishni tezlashtirish uchun kuzda tushgan barglarni o'roq mashinasi bilan maydalang. Shoxlanishni ochish va ko'proq havo aylanishini ta'minlash uchun olma daraxtlaringizni kesib oling.",
  "Apple___healthy" : "Sizning olma daraxtingiz sog'lom. \nUni avaylang",
  "Cherry_(including_sour)___healthy" : "Sizning gilos daraxtingiz sog'lom. \nUni avaylang",
  "Grape_healthy" : "Sizning uzum tokingiz sog'lom. \nUni avaylang",
  "Corn_(maize)___healthy'":"Sizning makkajo'xoringiz sog'lom. \nUni avaylang",
  "Peach___healthy":"Sizning shaftoli daraxtingiz sog'lom. \nUni avaylang",
  "Pepper,_bell___healthy":"Sizning qalampiringiz sog'lom. \nUni avaylang",
  "Potato___healthy":"Sizning kartoshkangiz sog'lom. \nUni avaylang",
  "Strawberry___healthy":"Sizning qulupnayingiz sog'lom. \nUni avaylang",
  "Tomato___healthy":"Sizning pamidoringiz sog'lom. \nUni avaylang",
  "Cherry_Powdery_mildew" : "1 litr suv bilan aralashtirilgan 1/4 choy qoshiq pishirish soda spreyi qo'llang. Barglardagi qo'ziqorinning dastlabki belgilarida har hafta o'simliklarni püskürtmek o'simliklarni keyingi zararlardan himoya qilishi mumkin. Savdoda mavjud bo'lgan organik davolash usuli bo'lgan neem yog'idan foydalaning.",
  "Grape___Black_rot":"Yorliqdagi ko'rsatmalarga muvofiq miklobutanil yoki kaptan kabi fungitsidni qo'llang. Qora chirigan tuzalib ketgunga qadar, fungitsidni ikki haftalik interval bilan qayta qo'llang. Ayni paytda, o'simlikni diqqat bilan tekshiring va qo'shimcha zararlangan joylarni olib tashlash uchun steril pichoqni ishlating. Ularning shifo topishiga yordam berish uchun yangi kesiklarga fungitsid pastasini qo'llang.",
  "Grape___Esca_(Black_Measles)":"Esca nomi bilan ham tanilgan uzum qora qizamiq uzoq vaqtdan beri uzum yetishtiruvchilarni qiynab kelayotgan kasallikdir. Bu kasallikka qarshi kurashish uchun quyidagi chora-tadbirlarni ko‘rishingiz mumkin: \nBudama: Kuchli yog‘ingarchilik davrida sporalar tarqalib ketishi mumkin bo‘lgan davrda kesishdan saqlaning. Yozning oxirida tokning yaralangan qismlarini kesib tashlang.\nKasal qoldiqlarni olib tashlash: Uzumzordan kasal qoldiqlarni olib tashlang va ularni yo'q qiling2. Bu kasallikning tarqalishining oldini olishga yordam beradi.\nFungitsidlardan foydalanish: Tijoriy uzum yetishtiruvchi ohak oltingugurtdan foydalanishi mumkin va qizamiqni ushlab turish uchun har qanday Azizillo jarohatlariga yopishtirishingiz mumkin bo'lgan boshqa plomba moddalari mavjud.\nQayta o'sishi: Agar Agar kasallik og'ir bo'lsa, siz tokni bir necha kurtaklarigacha kesib, uni qayta o'stirishga harakat qilishingiz mumkin. \nMonitoring: Bahorda uzumzorni kuzatib boring va o'lik novdalar yoki bo'yli kurtaklar bor-yo'qligini qidiring.\nEsda tutingki, bular umumiy chora-tadbirlardir va samaradorlik fermaning o'ziga xos sharoitlariga qarab farq qilishi mumkin. Mintaqangizdagi eng yaxshi amaliyotlar uchun har doim mahalliy qishloq xo'jaligini kengaytirish xizmati yoki professional agronom bilan maslahatlashing. Bundan tashqari, har qanday pestitsidlar yoki fungitsidlardan foydalanganda har doim ishlab chiqaruvchining ko'rsatmalariga amal qiling.",
  "Grape_Isariopsis_Leaf_Spot":"O'simlik kuchini rag'batlantirish. O'simlik to'qimalarini quritishni rag'batlantirish uchun havo aylanishini oshiring (kesish, yupqalash, oraliq va begona o'tlarni boshqarish). Fungitsidlarni qo'llang (ayniqsa, birlamchi kasalliklarni nazorat qilish uchun ishlatiladigan erta mavsumdagi fungitsidlar).",
  "Corn_(maize)___Common_rust_":"Ekish paytida donador yoki urug'li insektitsiddan foydalaning. Optimum ® AcreMax ® Xtreme yoki Qrome ® mahsulotlari kabi CRW ga qarshi nazorat qilishning bir nechta ta'sir usullariga ega mahsulotni eking. Qo'shimcha himoya qilish uchun yuqori darajadagi insektitsid urug'ini davolash bilan makkajo'xori mahsulotidan foydalaning.",
  "Corn_fallarmyworm":"Qo'lda olib tashlash: Agar sizning o'simliklaringizda vaqti-vaqti bilan boshoqli makkajo'xori qurti bo'lsa, siz zararlangan quloqlarning uchlarini kesib, uni nazorat qilishingiz mumkin. Mineral moy: Ipak paydo bo'lgandan keyin besh-etti kun o'tgach, ipaklarga mineral moy surting. Insektitsidlar: makkajo'xori quloq qurtlarini nazorat qilish uchun ishlatiladigan tipik insektitsidlar karbaril yoki permetrin kabi piretroidlardir.",
  'Corn_leaf_beetle': "1.Oʻsimliklardan qoʻngʻizlarni olib tashlang.\n2.Ekni almashtirish, matolarni tushirish va yotoqlaringizni oʻsimlik qoldiqlaridan tozalash kabi madaniy nazoratdan foydalaning.\n3.Yirtqich hasharotlarni jalb qilish kabi biologik nazorat vositalari.\n4.Soʻnggi chora sifatida, piretrinlar, spinosad va neem yog'idan foydalaning.\n5.Organik yetishtiruvchilar rotenon, piretrum yoki neemdan foydalanishlari mumkin, organik ravishda o'smaydiganlar esa karbaril va permetrindan foydalanishlari mumkin.",
  'Corn_(maize)___Northern_Leaf_Blight': "1. Chidamli makkajoʻxori duragaylaridan foydalaning.\n2. Kerakli hollarda anʼanaviy ishlov berish.\n3.Almashlab ekish.\n4.Makkajoʻxoridagi barglarning kuyishini Captan yoki zineb sepish orqali samarali nazorat qilish mumkin.\n5.Sanitariya va almashlab ekishni qoʻllash kerak. .",
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': "Oʻsimliklar orasidagi boʻshliqni kengaytirish orqali yaxshi shamollatishni davom eting.\n2.Oʻrim-yigʻimdan keyin chuqur haydab, barcha oʻsimlik qoldiqlarini koʻmib tashlang.\n3.Boshqa oʻsimliklar bilan uzoq muddatli almashlab ekishni rejalashtiring.",
  "Corn_(maize)___healthy":"",
  'Corn_streak_virus': "1.Virus kasalliklarini kimyoviy davolash yo'q.\n2.Vektorlar populyatsiyasining qisqarishi, odatda, kasallikning yuqish tezligining pasayishiga olib keladi.",
  "Corn_grasshoper":"Yozning oxirida yoki kuzda katta yoshli kuya tuxum qo'yish boshlanishidan oldin dala chetlari bo'ylab o't va begona o'tlarni o'ldirish keyingi yil kasallanishni kamaytirishga yordam beradi. O'tlarni kesish, yoqish yoki gerbitsidlardan foydalanish samarali.",
  "Peach___Bacterial_spot" : "Ushbu kasallikni davolash uchun ba'zi paxtakorlar yanvar yoki fevral oylarida kesishni taklif qilishadi. Saratondan kamida 12 dyuym pastda olib tashlang va zararlangan daraxt materialini tashlang1. Yana bir taklif - mis fungitsidini barg tushganda qo'llash1. Bakterial dog'larning rivojlanishiga yordam beradigan atrof-muhit sharoitlari harorat 75 ° F1 dan yuqori bo'lgan kuchli yomg'irlarni o'z ichiga oladi. Issiq, quruq ob-havoning uzoq muddatlari kasallik xavfini kamaytiradi.",
  "Pepper,_bell___Bacterial_spot":"Ushbu kasallikni davolash uchun o'simlikning zararlangan qismlarini olib tashlang va ularni bog'dan uzoqroqqa olib boring2. Fosfor va kaliyga boy oʻgʻitlar bilan oʻgʻitlash2. O'simlikning zararlangan qismlarini organik fungitsid bilan püskürtün2. Har doim toza qo'llar bilan ishlang va o'simliklarning o'zaro ifloslanishidan saqlaning2.",
  "Potato___Early_blight": "Davolash kasallikka chidamli kartoshka navlarini ekish orqali oldini olishni o'z ichiga oladi3. Ertapishar navlarga qaraganda kechpisharlari chidamliroqdir3. Yuqori sug'orishdan saqlaning va barglarning iloji boricha tezroq qurib qolishiga imkon berish uchun o'simliklar o'rtasida etarli havoni ta'minlang3. Ikki yillik almashlab ekishni mashq qiling3.",
  "Potato___Late_blight" : "Kartoshka kasalligini yo'qotish uchun, agar ozgina barglar zararlangan bo'lsa, zararlangan barglarni olib tashlang va yo'q qiling4. Bir vegetatsiya davrida to'rt martagacha ishlatilishi mumkin bo'lgan Bayer Garden Blight Control bilan püskürtün4. INFEKTSION tarqalib ketgan bo'lsa, barglar va poyalarni kesib oling4. Barcha o'lik yoki o'layotgan o'simliklarni olib tashlang va kartoshkani qazib oling4. Ularni bog'ingizdan uzoqroqqa tashlang4.",
  "Strawberry___Leaf_scorch": "1.Ushbu kasallikni davolash uchun o'simlikning barcha zararlangan qismlarini olib tashlang va yo'q qiling. \n2. Qopqoq ostida o'sadigan o'simliklar uchun shamollatishni va iloji bo'lsa, o'simliklar orasidagi bo'shliqni oshiring. \n3. Barglarni namlashdan saqlanishga harakat qiling. o'simliklarni sug'orishda, ayniqsa kechqurun sug'orishda. \n4. Qulupnay kasalliklarini nazorat qilish uchun mis asosidagi fungitsidlardan foydalanish mumkin.",  "T_Bacterial_spot": "Ushbu kasallikni davolash uchun o'simliklar atrofidagi tuproqni mulch bilan yoping va o'simliklarni bir joyga to'plamang. Barglar nam bo'lganda, yuqoridan sug'orishdan va o'simliklar bilan ishlashdan saqlaning. Yangi o'sishni qo'llab-quvvatlash uchun o'simliklarni urug'lantirish. Alomatlar birinchi marta paydo bo'lganda, yorliqli mis fungitsid bilan püskürtün. Infektsiyalangan o'simliklarni olib tashlang va barcha zararlangan ekin qoldiqlarini tashlang.",
  "Tomato___Leaf_Mold" : "Ushbu kasallikni davolash uchun o'rim-yig'imdan keyin barcha ekin qoldiqlarini olib tashlang va yo'q qiling. Ekin mavsumi orasida issiqxonani sanitarizatsiya qiling. Barglarning namligini kamaytirish uchun fanatlardan foydalaning va yuqoridan sug'orishdan saqlaning. Bundan tashqari, ventilyatsiyani oshirish uchun o'simliklarni qoziq va kesish. Agar kasallik aniqlansa, infektsiyaning birinchi belgisida ishlab chiqaruvchining ko'rsatmalariga muvofiq fungitsidni qo'llang.",
  "Tomato___Spider_mites Two-spotted_spider_mite":"Ushbu kasallikni davolash uchun ularni o'simlikning poyasi va barglaridan bog 'shlangi bilan püskürtün. Shundan so'ng, siz o'simliklarni tabiiy pestitsid bo'lgan neem yog'i bilan püskürtishingiz kerak. O'rgimchak oqadilar yo'qolguncha davolanishni har 7 kunda bir marta takrorlashingiz kerak.",
  "Tomato_leaf_blight" : "Pomidor kuyishini to'xtatish uchun barcha zararlangan barglarni olib tashlang, ularni axlatga tashlang yoki ularni yoqing. Qo'ziqorin sporalarining o'sishiga yo'l qo'ymaslik uchun pomidorning asosini mulchalang. Agar kuyish pomidor o'simligining poyalariga ta'sir qilgan bo'lsa, fungitsidni qo'llang. Nihoyat, infektsiyalangan pomidorlar ekilgan tuproqni qayta ishlatmang.",
  "Tomato_leaf_curl":"1. Barglar tushishi bosqichida oʻsimlikka suyultirilgan mis fungitsidi bilan yaxshilab püskürtün.\n2.Davolashni kech uyqu va kurtaklarning shishishi bosqichida takrorlang.\n3.Oʻsimlikni pushti kurtak bosqichida uchinchi marta davolang.\n4 .Agar foydalanishga tayyor fungitsiddan foydalansangiz, o'simlikni faol o'sish davrida barglarning burishishi bilan davolash uchun oqim nuqtasiga qadar püskürtün.",
  "Tomato___Tomato_mosaic_virus":"1.Barcha zararlangan oʻsimliklarni olib tashlang va ularni yoʻq qiling.\n2.Ularni kompost uyasiga qoʻymang, chunki virus zararlangan oʻsimlik moddalarida saqlanib qolishi mumkin.\n3.Kasallangan oʻsimliklarni yoqib yuboring yoki axlat bilan birga tashlab yuboring.\n4.Monitoring. qolgan o'simliklaringizni, ayniqsa kasal o'simliklar yaqinida joylashgan o'simliklarni yaqindan saqlang.\n5.Har foydalanishdan keyin bog'dorchilik vositalarini dezinfeksiya qiling.",
  "Tomato___Septoria_leaf_spot":"1. Ta'sirlangan o'simliklar va o'simlik qismlarini olib tashlang.\n2.Organik fungitsiddan foydalaning.\n3.Kimyoviy muqobillarni ko'rib chiqing.\n4.Kasallangan o'simlik materialini olib tashlash va yo'q qilish orqali yaxshi o'simlik gigienasiga rioya qiling.\n5.Kuzda o'simlik qoldiqlarini tozalang. \n6.Kasalliksiz urugʻlar va kasalliklarga chidamli navlardan foydalaning.\n7. Ertalab o'simliklarni sug'orib turing, barglarni namlashdan saqlaning, chunki bu zamburug'larning o'sishiga yordam beradi.\n8.Tuproqdagi sporalarning barglar ustiga sachramasligi uchun mulchdan foydalaning.\n9. Septoria barglari dog'ini oldini olish va nazorat qilish uchun mis asosidagi fungitsidlar, neem yog'i yoki oltingugurt spreylaridan foydalanishni o'ylab ko'ring.",
  "Tomato_verticulium_wilt":"1. Daraxtlar va butalar uchun verticillium solgunligi bilan davolash o'simlikka chidamliligini oshirish uchun eng yaxshi g'amxo'rlik qilishga qaratilgan. \n2. Oʻsimlikni muntazam sugʻorib turing, iloji boʻlsa, tushdan keyin soya qiling.\n3.Azot va fosfor miqdori kam boʻlgan oʻgʻitlarni jadval asosida oʻgʻitlang.\n4. Qurigan va qurib qolgan novdalarni kesib oling5.",
  "Tomato___Bacterial_spot":"1.Oʻsimliklar hoʻl boʻlganda ularga ishlov berishdan saqlaning.\n2.Mulchdan foydalaning: Oʻsimliklar atrofidagi tuproqni mulch bilan yoping va oʻsimliklarni bir-biriga toʻplamang.\n3.Sugʻorish: Barglari nam boʻlganida oʻsimliklarni yuqoridan sugʻorishdan va ular bilan ishlashdan saqlaning.\n4 .Urugʻlantirish: Yangi oʻsishni qoʻllab-quvvatlash uchun oʻsimliklarni urugʻlantiring.\n4.Fungitsidlardan foydalanish: Alomatlar birinchi marta paydo boʻlganda, yorliqli mis fungitsidi bilan püskürtün. \nUy egalari uchun mis mahsulotlari yoki mis va mankozeb ro'yxatga olingan va pomidorning bakterial dog'larini nazorat qilish uchun samarali hisoblanadi. Tijorat yetishtiruvchilar uchun issiqxona transplantatsiyasidagi bakterial dog'ni streptomitsin yordamida nazorat qilish kasallikning dalada tarqalishini oldini oladi.\nKasallangan o'simliklarni olib tashlash: Kasallangan o'simliklarni olib tashlang va barcha zararlangan ekin qoldiqlarini tashlang3.",
  "Tomato___Early_blight":"Barglarning erta zararlanishi \n\nZarar belgilari Nam ob-havo va yomgir yogishi rivojlanishiga yordam beradi. Kasallikning avj olishlari yomgirda sodir bolgan kuchli yirtqichlardan kuzatilishi mumkin. \nInfektsiyalangan kasalliklarda sargish halo bilan oralgan, kichik, suvga namlangan, dumaloq doglar paydo boladi. yashil mevalarda. Avvaliga suv bilan namlangan mayda dog paydo boladi, ular narxi kotariladi va sakkizdan sakkizdan tort dyuymgacha kattalashadi.\nPishgan mevalarka zarar emas. Urugning zararkunandalarida qolib, bakteriyalar bilan ifloslanib, bir muddat urug qoshimchalarida qoladi. nBakterial hujayralar zararlangan osimlik qoldiqlari va uruglarida (ichki va qoshimchada), Solanum nigim kabi solanaceous otlarda omon qoladi.\nIklamchi: yomgir chayqalishi orqali bakteriya uzatiladi\nQulay oldini\nNam ob-havo va yomgir. ir yogishi\nYuqori namlik yoki doimiy shudring.",
  "Tomato___Late_blight":"Pamidor barglarining kuyishini davolash uchun quyidagi choralarni ko’rishni maslahat beraman:\n\nO’simlikni muntazam tekshirish: Pamidor barglarining kuyishi, odatda, zararli hasharotlar yoki kasalliklar tufayli bo’ladi. Shuning uchun, o’simliklarni muntazam ravishda tekshirib, kuyish belgilarini aniqlash muhimdir.\n\nZararli hasharotlarni yo’q qilish: Agar zararli hasharotlar aniqlansa, ularni yo’q qilish uchun zararsiz hasharotlar yoki biologik preparatlarni ishlatish mumkin.\n\nDorilar ishlatish: Agar kasallik aniqlansa, kasallik turi va darajasiga qarab, mos keladigan dori yoki davolash usulini tanlash kerak.\n\nAmmo, konkret dorilar haqida maslahat berish uchun, sizga to’g’ri javob berish uchun qo’shimcha ma’lumotlarni qidirishim kerak. Bu kasallikning turi, darajasi va o’simlikning joriy holati kabi ko’plab omillar dori turini va uni qanday ishlatish kerakligini ta’sir qiladi1. Shuning uchun, iltimos, o’simlikni kasallikdan himoya qilish bo’yicha mutaxassis bilan bog’laning yoki mahalliy o’simlikni himoya qilish xizmatiga murojaat qiling.",
  "Tomato___Target_Spot":"Pamidorning zararlangan joyi",
  "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Pomidorning sariq barglari jingalak virusi",
  "Cherry_(including_sour)___Powdery_mildew":""
}

urlss = {
  'Apple___Black_rot': 'https://youtu.be/739x1CDE3QE?si=-zsVYJHxYrW9vz2q',
  'Apple___Cedar_apple_rust': 'https://www.youtube.com/watch?v=ynCBHri2zDk&pp=ygUgQXBwbGUgQ2VkYXIgYXBwbGUgcnVzdCB0cmVhdG1lbnQ%3D',
  'Apple___healthy': "Olma sog'lom",
  'Apple___Apple_scab': "https://www.youtube.com/watch?v=SMS2jHqACrY&pp=ygUcQXBwbGVfX19BcHBsZV9zY2FiIHRyZWF0bWVudA%3D%3D",
  'Cherry_(including_sour)___Powdery_mildew': 'https://www.youtube.com/watch?v=N0NJsaCeF8k&pp=ygUzJ0NoZXJyeV8oaW5jbHVkaW5nX3NvdXIpX19fUG93ZGVyeV9taWxkZXcgdHJlYXRtZW50',
  'Cherry_(including_sour)___healthy': "Gilos sog'lom",
  'Grape___Esca_(Black_Measles)': 'https://www.youtube.com/watch?v=WVk21qyDeFw&pp=ygUZZ3JhcGUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D',
  'Grape___Black_rot': 'https://www.youtube.com/watch?v=WVk21qyDeFw&pp=ygUZZ3JhcGUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D',
  'Grape_Isariopsis_Leaf_Spot': "https://www.youtube.com/watch?v=WVk21qyDeFw&pp=ygUZZ3JhcGUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D",
  'Grape_healthy': "Sog'lom uzum",
  'Corn_(maize)___Common_rust_': "https://www.youtube.com/watch?v=EcUb1w1BAM8&pp=ygUZbWFpemUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D",
  'Corn_fallarmyworm': "https://www.youtube.com/watch?v=EcUb1w1BAM8&pp=ygUZbWFpemUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D",
  'Corn_grasshoper': "https://www.youtube.com/watch?v=EcUb1w1BAM8&pp=ygUZbWFpemUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D",
  'Corn_(maize)___healthy': "https://www.youtube.com/watch?v=vCHedpeKoXU&pp=ygUNbWFpemUgaGVhbHRoeQ%3D%3D",
  'Corn_leaf_beetle': "https://www.youtube.com/watch?v=EcUb1w1BAM8&pp=ygUZbWFpemUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D",
  'Corn_(maize)___Northern_Leaf_Blight': "https://www.youtube.com/watch?v=EcUb1w1BAM8&pp=ygUZbWFpemUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D",
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': "https://www.youtube.com/watch?v=EcUb1w1BAM8&pp=ygUZbWFpemUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D",
  'Corn_streak_virus': "https://www.youtube.com/watch?v=EcUb1w1BAM8&pp=ygUZbWFpemUgZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D",
  'Peach___Bacterial_spot': "https://www.youtube.com/watch?v=iRu2kApNg0A&pp=ygUZcGVhY2ggZGlzZWFzZXMgdHJlYXRtZW50IA%3D%3D",
  'Peach___healthy': "https://www.youtube.com/watch?v=wgkKjTARqsw&pp=ygUQc2hhZnRvbGkgc29nJ2xvbQ%3D%3D",
  'Pepper,_bell___healthy': "https://www.youtube.com/watch?v=OxoYHQQQWc8&pp=ygUVcWFsYW1waXIgeWV0aXNodGlyaXNo",
  'Pepper,_bell___Bacterial_spot': "https://youtu.be/sfBBKZF1IWI?si=CLkx8u01-Z5NDmYQ'",
  'Potato___Early_blight': 'https://www.youtube.com/watch?v=kCo2U3PJIik&pp=ygUVUG90YXRvX19fRWFybHlfYmxpZ2h0',
  'Potato___Late_blight': 'https://www.youtube.com/watch?v=kCo2U3PJIik&pp=ygUVUG90YXRvX19fRWFybHlfYmxpZ2h0',
  'Potato___healthy': "https://www.youtube.com/watch?v=ym0mmubnHfs&pp=ygUQUG90YXRvX19faGVhbHRoeQ%3D%3D",
  'Strawberry___Leaf_scorch': 'https://www.youtube.com/watch?v=po2lxHLr8DQ&pp=ygUYU3RyYXdiZXJyeV9fX0xlYWZfc2NvcmNo',
  'Strawberry___healthy': "https://www.youtube.com/watch?v=qqoy-mVFNSo&pp=ygUUU3RyYXdiZXJyeV9fX2hlYWx0aHk%3D",
  'Tomato___Bacterial_spot': 'https://www.youtube.com/watch?v=jONPVKSvFW0&pp=ygUXVG9tYXRvX19fQmFjdGVyaWFsX3Nwb3Q%3D',
  'Tomato___Leaf_Mold': 'https://www.youtube.com/watch?v=ZEjLkos08cw&pp=ygUVVG9tYXRvX19fU3BpZGVyX21pdGVz',
  'Tomato___Spider_mites Two-spotted_spider_mite': "https://www.youtube.com/watch?v=ZEjLkos08cw&pp=ygUVVG9tYXRvX19fU3BpZGVyX21pdGVz",
  'Tomato___healthy': "https://www.youtube.com/watch?v=M4T3bGDEyHY&pp=ygUQVG9tYXRvX19faGVhbHRoeQ%3D%3D",
  'Tomato___Early_blight': 'https://www.youtube.com/watch?v=rG7YdE3JJwg&pp=ygUVVG9tYXRvX19fRWFybHlfYmxpZ2h0',
  "Tomato___Late_blight":"https://www.youtube.com/watch?v=rG7YdE3JJwg&pp=ygUVVG9tYXRvX19fRWFybHlfYmxpZ2h0",
  'Tomato_leaf_curl': 'https://www.youtube.com/watch?v=D-58aAFIyCQ&pp=ygUQVG9tYXRvX2xlYWZfY3VybA%3D%3D',
  'Tomato___Tomato_mosaic_virus': 'https://www.youtube.com/watch?v=_w5GwfbVytE&pp=ygUcVG9tYXRvX19fVG9tYXRvX21vc2FpY192aXJ1cw%3D%3D',
  'Tomato___Septoria_leaf_spot': "https://www.youtube.com/watch?v=_w5GwfbVytE&pp=ygUcVG9tYXRvX19fVG9tYXRvX21vc2FpY192aXJ1cw%3D%3D",
  'Tomato_verticulium_wilt': "https://www.youtube.com/watch?v=_w5GwfbVytE&pp=ygUcVG9tYXRvX19fVG9tYXRvX21vc2FpY192aXJ1cw%3D%3D",
  "Tomato___Target_Spot":"https://www.youtube.com/watch?v=_w5GwfbVytE&pp=ygUcVG9tYXRvX19fVG9tYXRvX21vc2FpY192aXJ1cw%3D%3D",
  "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "https://www.youtube.com/watch?v=_w5GwfbVytE&pp=ygUcVG9tYXRvX19fVG9tYXRvX21vc2FpY192aXJ1cw%3D%3D",

}
